/*
 * TimelineWorkspaceDock.cpp — Dock/workspace persistence functions extracted
 * from TimelineWorkspace.cpp.
 *
 * Contains: saveDockLayout(), restoreDockLayout(), resetToDefaultDockLayout(),
 * doResetToDefaultDockLayout(), showEvent().
 */

#include "panels/timeline/TimelineWorkspace.h"
#include "panels/timeline/DockLayoutManager.h"

#include "panels/monitors/ProgramMonitor.h"

#include "Settings.h"

#include <QApplication>
#include <QBoxLayout>
#include <QCoreApplication>
#include <QDockWidget>
#include <QMainWindow>
#include <QDataStream>
#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QSettings>
#include <QTemporaryDir>
#include <QTimer>

#include <spdlog/spdlog.h>

namespace rt {

void TimelineWorkspace::saveDockLayout(QSettings& settings)
{
    if (!m_dockLayoutManager) return;

    // If a panel is maximized, the inner QMainWindow's dock layout is broken:
    // the maximized dock has been reparented out and all other docks hidden.
    // Save using the pre-maximize snapshot so the restored layout is correct.
    if (m_panelMaximized && !m_dockStateBeforeMaximize.isEmpty()) {
        spdlog::info("saveDockLayout: panel is maximized, using pre-maximize dock state ({} bytes)",
                     m_dockStateBeforeMaximize.size());
        m_dockLayoutManager->save(settings, m_dockStateBeforeMaximize);
    } else {
        m_dockLayoutManager->save(settings);
    }
}

bool TimelineWorkspace::restoreDockLayout(QSettings& settings)
{
    return m_dockLayoutManager ? m_dockLayoutManager->restore(settings) : false;
}

void TimelineWorkspace::resetToDefaultDockLayout()
{
    if (!m_innerMainWindow || m_defaultDockState.isEmpty()) return;

    // If the widget is not yet visible (e.g. called from applyDefaultLayout()
    // during startup before the Timeline page is shown), defer the actual
    // reset until showEvent so that Qt's dock widget restoreState() has a
    // valid window to work with.  Without this deferral, docks can end up
    // improperly positioned or hidden — manifesting as a timeline-maximized
    // layout with all other panels invisible.
    if (!isVisible() || width() < 100 || height() < 100) {
        spdlog::info("resetToDefaultDockLayout: widget not visible, deferring");
        m_pendingDefaultLayoutReset = true;
        return;
    }

    doResetToDefaultDockLayout();
}

void TimelineWorkspace::doResetToDefaultDockLayout()
{
    if (!m_innerMainWindow) return;

    // ── Try loading the user's canonical "USE_AS_DEFAULT" preset ────────
    // This is the designated default layout for ALL versions (dev, build,
    // published).  It is saved via Window > Workspace > Save Workspace as...
    // under the name "USE_AS_DEFAULT" and stored in QSettings under
    // WorkspacePresets/USE_AS_DEFAULT.
    {
        auto s = rt::appSettings();
        s.beginGroup(QStringLiteral("WorkspacePresets/USE_AS_DEFAULT"));
        bool hasPreset = !s.childKeys().isEmpty() ||
                         !s.childGroups().isEmpty();
        if (hasPreset) {
            spdlog::info("doResetToDefaultDockLayout: loading "
                         "USE_AS_DEFAULT preset");
            // Let the DockLayoutManager fully restore the saved state
            // (handles edge columns, splitter sizes, dock positions, etc.).
            if (m_dockLayoutManager) {
                m_dockLayoutManager->restore(s);
            }
            s.endGroup();
            // Recovery: refresh Program Monitor after dock layout change
            if (m_programMonitor) {
                QTimer::singleShot(0, this, [this]() {
                    m_programMonitor->resetViewState();
                });
            }
            return;
        }
        s.endGroup();
    }

    // ── Fall back to bundled default_layout.bin ─────────────────────────
    // This file is generated by running:
    //   roundtable.exe --load-preset USE_AS_DEFAULT --capture-workspace assets/default_layout.bin
    // and ships with the installer so published versions get the same
    // canonical layout as the dev build.  It is also saved on every close
    // so the installed version stays up to date.
    {
        QString bundledPath = QCoreApplication::applicationDirPath()
            + QStringLiteral("/assets/default_layout.bin");
        if (QFile::exists(bundledPath)) {
            spdlog::info("doResetToDefaultDockLayout: loading bundled "
                         "layout from {}", bundledPath.toStdString());
            QFile file(bundledPath);
            if (file.open(QIODevice::ReadOnly)) {
                QDataStream stream(&file);
                stream.setVersion(QDataStream::Qt_6_5);
                QByteArray iniData;
                stream >> iniData;
                file.close();
                if (!iniData.isEmpty()) {
                    QTemporaryDir tmpDir;
                    QString iniPath = tmpDir.filePath("workspace.ini");
                    {
                        QFile iniFile(iniPath);
                        if (iniFile.open(QIODevice::WriteOnly)) {
                            iniFile.write(iniData);
                            iniFile.close();
                        }
                    }
                    QSettings fileSettings(iniPath, QSettings::IniFormat);
                    fileSettings.beginGroup("workspace/last_session");
                    if (m_dockLayoutManager)
                        m_dockLayoutManager->restore(fileSettings);
                    fileSettings.endGroup();
                    // Recovery: refresh Program Monitor after dock layout change
                    if (m_programMonitor) {
                        QTimer::singleShot(0, this, [this]() {
                            m_programMonitor->resetViewState();
                        });
                    }
                    return;
                }
            }
        }
    }

    // ── Fall back to bare programmatic default ──────────────────────────
    if (m_defaultDockState.isEmpty()) return;

    if (m_panelMaximized) {
        m_panelMaximized = false;
        m_maximizedWidget = nullptr;
        m_maximizedDock = nullptr;
        m_dockStateBeforeMaximize.clear();
    }

    // Destroy any edge columns in the splitter
    if (m_edgeSplitter) {
        QList<QMainWindow*> edgeCols;
        for (int i = 0; i < m_edgeSplitter->count(); ++i) {
            auto* mw = qobject_cast<QMainWindow*>(m_edgeSplitter->widget(i));
            if (mw && mw != m_innerMainWindow)
                edgeCols.append(mw);
        }
        for (auto* mw : edgeCols) {
            for (auto* dock : mw->findChildren<QDockWidget*>()) {
                mw->removeDockWidget(dock);
                dock->setParent(this);
                dock->hide();
            }
            mw->hide();
            mw->setParent(nullptr);
            delete mw;
        }
    }

    // Show all dock widgets (in case some were closed)
    for (auto it = m_dockWidgets.constBegin(); it != m_dockWidgets.constEnd(); ++it) {
        auto* dock = it.value();
        if (dock->isFloating()) {
            dock->setFloating(false);
        }
        m_innerMainWindow->addDockWidget(Qt::TopDockWidgetArea, dock);
        dock->setVisible(true);
    }

    // Restore the initial programmatic dock state
    m_innerMainWindow->restoreState(m_defaultDockState, 4);

    // Make all docks visible again after restore
    for (auto it = m_dockWidgets.constBegin(); it != m_dockWidgets.constEnd(); ++it)
        it.value()->setVisible(true);

    spdlog::info("Dock layout reset to programmatic default");

    // ── Recovery: refresh Program Monitor after dock reset ───────────
    // Dock state restoration can leave the Program Monitor's viewport
    // stack, transform overlay geometry, native HWND clipping region, or
    // composite pipeline in a broken state.  Force a full reset so the
    // composite preview recovers from black screen / stale overlays /
    // wrong panel content / crosshair reticle without requiring a restart.
    if (m_programMonitor) {
        QTimer::singleShot(0, this, [this]() {
            m_programMonitor->resetViewState();
        });
    }
}

void TimelineWorkspace::showEvent(QShowEvent* event)
{
    QWidget::showEvent(event);

    // If a default layout reset was deferred (because the widget was hidden
    // when resetToDefaultDockLayout() was called), apply it now that the
    // widget has real geometry so restoreState() works correctly.
    if (m_pendingDefaultLayoutReset) {
        m_pendingDefaultLayoutReset = false;
        if (m_dockLayoutManager)
            m_dockLayoutManager->clearPendingState();
        updateGeometry();
        QApplication::processEvents(QEventLoop::ExcludeUserInputEvents);
        spdlog::info("showEvent: applying deferred default dock layout reset");
        doResetToDefaultDockLayout();
    } else if (m_dockLayoutManager) {
        // Apply any deferred dock layout state (from saved-layout restore).
        m_dockLayoutManager->applyPendingState();
    }
}

// ═════════════════════════════════════════════════════════════════════════════

} // namespace rt
